### ISSUE TITLE
Tilt integration

### ISSUE THREAD

**Issue by noraj** [yivo/pug-ruby#5]
Could you work with Tilt (Generic interface to multiple Ruby template engines) team to add pug-ruby to community supported template.

I also asked at their side. https://github.com/rtomayko/tilt/issues/346

## Thanks

This project is awesome! I always dream of being able to use pug in ruby because all template languages in Ruby sucks, only Slim has similar syntax but does not ship all the features of pug.

**Comment by yivo** [comment]
Hi @noraj,

Thanks for your issue.

I will take a look later once I have more free time.

Keep in mind Jade/Pug is not a replacement for Slim, you will not be able to use Ruby in Jade/Pug template. It is designed be used as JST client side templates.

**Comment by noraj** [comment]
Pug native Case, Conditionals, Includes, Inheritance, Iteration, Mixins should be enough to not have to use Ruby code in most case.
